// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Vault struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}
