// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createVault = `-- name: CreateVault :one
INSERT INTO vaults (name, description)
VALUES (?, ?)
RETURNING id, name, description, created_at
`

type CreateVaultParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, createVault, arg.Name, arg.Description)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
